version: "3.9"
services:
  web_channel:
    build: web/
    command: daphne -b 0.0.0.0 -p 8001 mysite.asgi:application
    ports:
      - 8001:8001

  web_http:
    build: web/
    command: uwsgi --ini mysite.uwsgi.ini
    volumes:
      - static_data:/var/www/mysite/static/
      - uwsgi_data:/tmp/uwsgi/

  nginx:
     depends_on:
       - web_http
       - web_channel
     build: nginx/
     restart: always
     ports:
       - 8888:80
     volumes:
       - static_data:/var/www/mysite/static/:ro
       - uwsgi_data:/tmp/uwsgi/

  redis:
    image: redis
    command: redis-server
    restart: always
    ports:
      - 6379:6379

volumes:
  static_data:
  uwsgi_data:
  redis_data: